server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Aa725386@
  thymeleaf:
    cache: false
  banner:
    charset: UTF-8
    location: classpath:banner/banner.txt
    image:
      location: classpath:banner/banner.png
      invert: false
      height: 30
      width: 175
  messages:
    basename: language/messages